In [1]:
import numpy as np
import json
import re
import tensorflow as tf
import random
import spacy
nlp = spacy.load('en_core_web_sm')

In [2]:
with open('intents.json') as f:
    intents = json.load(f)

In [3]:
def preprocessing(line):
    line = re.sub(r'[^a-zA-z.?!\']', ' ', line)
    line = re.sub(r'[ ]+', ' ', line)
    return line

In [4]:
intents

{'intents': [{'intent': 'Greeting',
   'text': ['Hi',
    'Hi there',
    'Hola',
    'Hello',
    'Hello there',
    'Hya',
    'Hya there'],
   'responses': ['Hi human, please tell me your GeniSys user',
    'Hello human, please tell me your GeniSys user',
    'Hola human, please tell me your GeniSys user'],
   'extension': {'function': '', 'entities': False, 'responses': []},
   'context': {'in': '', 'out': 'GreetingUserRequest', 'clear': False},
   'entityType': 'NA',
   'entities': []},
  {'intent': 'GreetingResponse',
   'text': ['My user is Adam',
    'This is Adam',
    'I am Adam',
    'It is Adam',
    'My user is Bella',
    'This is Bella',
    'I am Bella',
    'It is Bella'],
   'responses': ['Great! Hi <HUMAN>! How can I help?',
    'Good! Hi <HUMAN>, how can I help you?',
    'Cool! Hello <HUMAN>, what can I do for you?',
    'OK! Hola <HUMAN>, how can I help you?',
    'OK! hi <HUMAN>, what can I do for you?'],
   'extension': {'function': 'extensions.gHumans.updateHum

{'intents': [{'intent': 'Greeting',
   'text': ['Hi',
    'Hi there',
    'Hola',
    'Hello',
    'Hello there',
    'Hya',
    'Hya there'],
   'responses': ['Hi human, please tell me your GeniSys user',
    'Hello human, please tell me your GeniSys user',
    'Hola human, please tell me your GeniSys user'],
   'extension': {'function': '', 'entities': False, 'responses': []},
   'context': {'in': '', 'out': 'GreetingUserRequest', 'clear': False},
   'entityType': 'NA',
   'entities': []},
  {'intent': 'GreetingResponse',
   'text': ['My user is Adam',
    'This is Adam',
    'I am Adam',
    'It is Adam',
    'My user is Bella',
    'This is Bella',
    'I am Bella',
    'It is Bella'],
   'responses': ['Great! Hi <HUMAN>! How can I help?',
    'Good! Hi <HUMAN>, how can I help you?',
    'Cool! Hello <HUMAN>, what can I do for you?',
    'OK! Hola <HUMAN>, how can I help you?',
    'OK! hi <HUMAN>, what can I do for you?'],
   'extension': {'function': 'extensions.gHumans.updateHum

In [5]:
# get text and intent title from json data
inputs, targets = [], []
classes = []
intent_doc = {}

for intent in intents['intents']:
    if intent['intent'] not in classes:
        classes.append(intent['intent'])
    if intent['intent'] not in intent_doc:
        intent_doc[intent['intent']] = []
        
    for text in intent['text']:
        inputs.append(preprocessing(text))
        targets.append(intent['intent'])
        
    for response in intent['responses']:
        intent_doc[intent['intent']].append(response)


In [6]:
inputs

['Hi',
 'Hi there',
 'Hola',
 'Hello',
 'Hello there',
 'Hya',
 'Hya there',
 'My user is Adam',
 'This is Adam',
 'I am Adam',
 'It is Adam',
 'My user is Bella',
 'This is Bella',
 'I am Bella',
 'It is Bella',
 'How are you?',
 'Hi how are you?',
 'Hello how are you?',
 'Hola how are you?',
 'How are you doing?',
 'Hope you are doing well?',
 'Hello hope you are doing well?',
 'Good thanks! My user is Adam',
 'Good thanks! This is Adam',
 'Good thanks! I am Adam',
 'Good thanks! It is Adam',
 'Great thanks! My user is Bella',
 'Great thanks! This is Bella',
 'Great thanks! I am Bella',
 'Great thanks! It is Bella',
 'What is my name?',
 'What do you call me?',
 'Who do you think I am?',
 'What do you think I am?',
 'Who are you talking to?',
 'What name do you call me by?',
 'Tell me my name',
 'What is your name?',
 'What could I call you?',
 'What can I call you?',
 'What do your friends call you?',
 'Who are you?',
 'Tell me your name?',
 'What is your real name?',
 'What is your

['Hi',
 'Hi there',
 'Hola',
 'Hello',
 'Hello there',
 'Hya',
 'Hya there',
 'My user is Adam',
 'This is Adam',
 'I am Adam',
 'It is Adam',
 'My user is Bella',
 'This is Bella',
 'I am Bella',
 'It is Bella',
 'How are you?',
 'Hi how are you?',
 'Hello how are you?',
 'Hola how are you?',
 'How are you doing?',
 'Hope you are doing well?',
 'Hello hope you are doing well?',
 'Good thanks! My user is Adam',
 'Good thanks! This is Adam',
 'Good thanks! I am Adam',
 'Good thanks! It is Adam',
 'Great thanks! My user is Bella',
 'Great thanks! This is Bella',
 'Great thanks! I am Bella',
 'Great thanks! It is Bella',
 'What is my name?',
 'What do you call me?',
 'Who do you think I am?',
 'What do you think I am?',
 'Who are you talking to?',
 'What name do you call me by?',
 'Tell me my name',
 'What is your name?',
 'What could I call you?',
 'What can I call you?',
 'What do your friends call you?',
 'Who are you?',
 'Tell me your name?',
 'What is your real name?',
 'What is your

In [7]:
len(inputs)

143

143

In [8]:
targets

['Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'NameQuery',
 'NameQuery',
 'NameQuery',
 'NameQuery',
 'NameQuery',
 'NameQuery',
 'RealNameQuery',
 'RealNameQuery',
 'RealNameQuery',
 'RealNameQuery',
 'RealNameQuery',
 'RealNameQuery',
 'RealNameQuery'

['Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'NameQuery',
 'NameQuery',
 'NameQuery',
 'NameQuery',
 'NameQuery',
 'NameQuery',
 'RealNameQuery',
 'RealNameQuery',
 'RealNameQuery',
 'RealNameQuery',
 'RealNameQuery',
 'RealNameQuery',
 'RealNameQuery'

In [9]:
classes

['Greeting',
 'GreetingResponse',
 'CourtesyGreeting',
 'CourtesyGreetingResponse',
 'CurrentHumanQuery',
 'NameQuery',
 'RealNameQuery',
 'TimeQuery',
 'Thanks',
 'NotTalking2U',
 'UnderstandQuery',
 'Shutup',
 'Swearing',
 'GoodBye',
 'CourtesyGoodBye',
 'WhoAmI',
 'Clever',
 'Gossip',
 'Jokes',
 'PodBayDoor',
 'PodBayDoorResponse',
 'SelfAware']

['Greeting',
 'GreetingResponse',
 'CourtesyGreeting',
 'CourtesyGreetingResponse',
 'CurrentHumanQuery',
 'NameQuery',
 'RealNameQuery',
 'TimeQuery',
 'Thanks',
 'NotTalking2U',
 'UnderstandQuery',
 'Shutup',
 'Swearing',
 'GoodBye',
 'CourtesyGoodBye',
 'WhoAmI',
 'Clever',
 'Gossip',
 'Jokes',
 'PodBayDoor',
 'PodBayDoorResponse',
 'SelfAware']

In [10]:
intent_doc

{'Greeting': ['Hi human, please tell me your GeniSys user',
  'Hello human, please tell me your GeniSys user',
  'Hola human, please tell me your GeniSys user'],
 'GreetingResponse': ['Great! Hi <HUMAN>! How can I help?',
  'Good! Hi <HUMAN>, how can I help you?',
  'Cool! Hello <HUMAN>, what can I do for you?',
  'OK! Hola <HUMAN>, how can I help you?',
  'OK! hi <HUMAN>, what can I do for you?'],
 'CourtesyGreeting': ['Hello, I am great, how are you? Please tell me your GeniSys user',
  'Hello, how are you? I am great thanks! Please tell me your GeniSys user',
  'Hello, I am good thank you, how are you? Please tell me your GeniSys user',
  'Hi, I am great, how are you? Please tell me your GeniSys user',
  'Hi, how are you? I am great thanks! Please tell me your GeniSys user',
  'Hi, I am good thank you, how are you? Please tell me your GeniSys user',
  'Hi, good thank you, how are you? Please tell me your GeniSys user'],
 'CourtesyGreetingResponse': ['Great! Hi <HUMAN>! How can I hel

{'Greeting': ['Hi human, please tell me your GeniSys user',
  'Hello human, please tell me your GeniSys user',
  'Hola human, please tell me your GeniSys user'],
 'GreetingResponse': ['Great! Hi <HUMAN>! How can I help?',
  'Good! Hi <HUMAN>, how can I help you?',
  'Cool! Hello <HUMAN>, what can I do for you?',
  'OK! Hola <HUMAN>, how can I help you?',
  'OK! hi <HUMAN>, what can I do for you?'],
 'CourtesyGreeting': ['Hello, I am great, how are you? Please tell me your GeniSys user',
  'Hello, how are you? I am great thanks! Please tell me your GeniSys user',
  'Hello, I am good thank you, how are you? Please tell me your GeniSys user',
  'Hi, I am great, how are you? Please tell me your GeniSys user',
  'Hi, how are you? I am great thanks! Please tell me your GeniSys user',
  'Hi, I am good thank you, how are you? Please tell me your GeniSys user',
  'Hi, good thank you, how are you? Please tell me your GeniSys user'],
 'CourtesyGreetingResponse': ['Great! Hi <HUMAN>! How can I hel

In [11]:
def tokenize_data(input_list):
    tokenizer = tf.keras.preprocessing.text.Tokenizer(filters='', oov_token='<unk>')
    
    tokenizer.fit_on_texts(input_list)
    
    input_seq = tokenizer.texts_to_sequences(input_list)

    input_seq = tf.keras.preprocessing.sequence.pad_sequences(input_seq, padding='pre')
    
    return tokenizer, input_seq

# preprocess input data
tokenizer, input_tensor = tokenize_data(inputs)

In [12]:
tokenizer

In [13]:
input_tensor

array([[ 0,  0,  0, ...,  0,  0, 54],
       [ 0,  0,  0, ...,  0, 54, 55],
       [ 0,  0,  0, ...,  0,  0, 70],
       ...,
       [ 0, 10,  2, ..., 52, 53, 22],
       [ 0, 10,  2, ..., 14, 69, 22],
       [ 0,  0,  0, ..., 68, 14, 69]])

array([[ 0,  0,  0, ...,  0,  0, 54],
       [ 0,  0,  0, ...,  0, 54, 55],
       [ 0,  0,  0, ...,  0,  0, 70],
       ...,
       [ 0, 10,  2, ..., 52, 53, 22],
       [ 0, 10,  2, ..., 14, 69, 22],
       [ 0,  0,  0, ..., 68, 14, 69]])

In [14]:
len(input_tensor[0])

9

9

In [15]:
len(input_tensor)

143

143

In [16]:
targets

['Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'NameQuery',
 'NameQuery',
 'NameQuery',
 'NameQuery',
 'NameQuery',
 'NameQuery',
 'RealNameQuery',
 'RealNameQuery',
 'RealNameQuery',
 'RealNameQuery',
 'RealNameQuery',
 'RealNameQuery',
 'RealNameQuery'

['Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'Greeting',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'GreetingResponse',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreeting',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CourtesyGreetingResponse',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'CurrentHumanQuery',
 'NameQuery',
 'NameQuery',
 'NameQuery',
 'NameQuery',
 'NameQuery',
 'NameQuery',
 'RealNameQuery',
 'RealNameQuery',
 'RealNameQuery',
 'RealNameQuery',
 'RealNameQuery',
 'RealNameQuery',
 'RealNameQuery'

In [17]:
len(targets)

143

143

In [18]:
def create_categorical_target(targets):
    word={}
    categorical_target=[]
    counter=0
    for trg in targets:
        if trg not in word:
            word[trg]=counter
            counter+=1
        categorical_target.append(word[trg])
    print(word)
    print(len(word))
    categorical_tensor = tf.keras.utils.to_categorical(categorical_target, num_classes=len(word), dtype='int32')
    return categorical_tensor, dict((v,k) for k, v in word.items())

# preprocess output data
target_tensor, trg_index_word = create_categorical_target(targets)

{'Greeting': 0, 'GreetingResponse': 1, 'CourtesyGreeting': 2, 'CourtesyGreetingResponse': 3, 'CurrentHumanQuery': 4, 'NameQuery': 5, 'RealNameQuery': 6, 'TimeQuery': 7, 'Thanks': 8, 'NotTalking2U': 9, 'UnderstandQuery': 10, 'Shutup': 11, 'Swearing': 12, 'GoodBye': 13, 'CourtesyGoodBye': 14, 'WhoAmI': 15, 'Clever': 16, 'Gossip': 17, 'Jokes': 18, 'PodBayDoor': 19, 'PodBayDoorResponse': 20, 'SelfAware': 21}
22
{'Greeting': 0, 'GreetingResponse': 1, 'CourtesyGreeting': 2, 'CourtesyGreetingResponse': 3, 'CurrentHumanQuery': 4, 'NameQuery': 5, 'RealNameQuery': 6, 'TimeQuery': 7, 'Thanks': 8, 'NotTalking2U': 9, 'UnderstandQuery': 10, 'Shutup': 11, 'Swearing': 12, 'GoodBye': 13, 'CourtesyGoodBye': 14, 'WhoAmI': 15, 'Clever': 16, 'Gossip': 17, 'Jokes': 18, 'PodBayDoor': 19, 'PodBayDoorResponse': 20, 'SelfAware': 21}
22


In [19]:
print('input shape: {} and output shape: {}'.format(input_tensor.shape, target_tensor.shape))


input shape: (143, 9) and output shape: (143, 22)
input shape: (143, 9) and output shape: (143, 22)


In [20]:
input_tensor

array([[ 0,  0,  0, ...,  0,  0, 54],
       [ 0,  0,  0, ...,  0, 54, 55],
       [ 0,  0,  0, ...,  0,  0, 70],
       ...,
       [ 0, 10,  2, ..., 52, 53, 22],
       [ 0, 10,  2, ..., 14, 69, 22],
       [ 0,  0,  0, ..., 68, 14, 69]])

array([[ 0,  0,  0, ...,  0,  0, 54],
       [ 0,  0,  0, ...,  0, 54, 55],
       [ 0,  0,  0, ...,  0,  0, 70],
       ...,
       [ 0, 10,  2, ..., 52, 53, 22],
       [ 0, 10,  2, ..., 14, 69, 22],
       [ 0,  0,  0, ..., 68, 14, 69]])

In [21]:
target_tensor

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]])

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]])

In [22]:
len(tokenizer.word_index)

128

128

In [23]:
# hyperparameters
epochs=50
vocab_size=len(tokenizer.word_index) + 1
embed_dim=512
units=128
target_length=target_tensor.shape[1]

In [24]:
target_length

22

22

In [25]:
vocab_size

129

129

In [26]:
# build RNN Model with tensorflow
model = tf.keras.models.Sequential([
    tf.keras.layers.Embedding(vocab_size, embed_dim),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(units, dropout=0.2)),
    tf.keras.layers.Dense(units, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(target_length, activation='softmax')
])

optimizer = tf.keras.optimizers.Adam(lr=1e-2)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()


Model: "sequential"
_________________________________________________________________
Model: "sequential"
 Layer (type)                Output Shape              Param #   
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 512)         66048     
                                                                 
 embedding (Embedding)       (None, None, 512)         66048     
 bidirectional (Bidirection  (None, 256)               656384    
                                                                 
 al)                                                             
 bidirectional (Bidirection  (None, 256)               656384    
                                                                 
 al)                                                             
 dense (Dense)               (None, 128)               32896     
                                    

In [27]:
early_stop = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=4)

# train the model
model.fit(input_tensor, target_tensor, epochs=epochs, callbacks=[early_stop])

Epoch 1/50
Epoch 1/50




5/5 [==============================] - 8s 71ms/step - loss: 3.0926 - accuracy: 0.0629
Epoch 2/50
Epoch 2/50
5/5 [==============================] - 0s 55ms/step - loss: 3.0534 - accuracy: 0.1818
Epoch 3/50
Epoch 3/50
5/5 [==============================] - 0s 59ms/step - loss: 3.0079 - accuracy: 0.2238
Epoch 4/50
Epoch 4/50
5/5 [==============================] - 0s 52ms/step - loss: 2.9814 - accuracy: 0.2028
Epoch 5/50
Epoch 5/50
5/5 [==============================] - 0s 53ms/step - loss: 2.8920 - accuracy: 0.2238
Epoch 6/50
Epoch 6/50
5/5 [==============================] - 0s 86ms/step - loss: 2.7958 - accuracy: 0.2517
Epoch 7/50
5/5 [==============================] - 0s 86ms/step - loss: 2.7958 - accuracy: 0.2517
Epoch 7/50
5/5 [==============================] - 0s 59ms/step - loss: 2.6285 - accuracy: 0.3566
Epoch 8/50
Epoch 8/50
5/5 [==============================] - 0s 44ms/step - loss: 2.3631 - accuracy: 0.4126
Epoch 9/50
Epoch 9/50
5/5 [==============================] - 0s 70ms/ste

In [28]:
def response(sentence):
    sent_seq = []
    doc = nlp(repr(sentence))
    
    # split the input sentences into words
    for token in doc:
        print(token)
        if token.text in tokenizer.word_index:
            sent_seq.append(tokenizer.word_index[token.text])

        # handle the unknown words error
        else:
            sent_seq.append(tokenizer.word_index['<unk>'])
    print(sent_seq)
    sent_seq = tf.expand_dims(sent_seq, 0)
    # predict the category of input sentences
    pred = model(sent_seq)
    print("++++++++++++++++++++++++++++++++++++++++++++++")
    print(pred)
    print("------------------------------------------------")


    pred_class = np.argmax(pred.numpy(), axis=1)
    print(pred_class)
    print("*****************************************************")
    # choice a random response for predicted sentence
    return random.choice(intent_doc[trg_index_word[pred_class[0]]]), trg_index_word[pred_class[0]]

# chat with bot
print("Note: Enter 'quit' to break the loop.")
while True:
    input_ = input('You: ')
    if input_.lower() == 'quit':
        break
    res, typ = response(input_)
    print('Bot: {} -- TYPE: {}'.format(res, typ))
    print()

Note: Enter 'quit' to break the loop.
Note: Enter 'quit' to break the loop.
You: greeting
'
greeting
'
[1, 1, 1]
++++++++++++++++++++++++++++++++++++++++++++++
tf.Tensor(
[[0.04250296 0.04093352 0.04866206 0.04591351 0.04322831 0.0523763
  0.0461831  0.05218948 0.04142904 0.04002801 0.04563521 0.04185225
  0.04162962 0.04619436 0.03973076 0.05075227 0.04396201 0.04965178
  0.04893561 0.04905329 0.04568824 0.04346833]], shape=(1, 22), dtype=float32)
------------------------------------------------
[5]
*****************************************************
Bot: You may call me Geni -- TYPE: NameQuery

'
greeting
'
[1, 1, 1]
++++++++++++++++++++++++++++++++++++++++++++++
tf.Tensor(
[[0.04250296 0.04093352 0.04866206 0.04591351 0.04322831 0.0523763
  0.0461831  0.05218948 0.04142904 0.04002801 0.04563521 0.04185225
  0.04162962 0.04619436 0.03973076 0.05075227 0.04396201 0.04965178
  0.04893561 0.04905329 0.04568824 0.04346833]], shape=(1, 22), dtype=float32)
-------------------------------